cmsplugin_newsplus/urls.py
from django.conf.urls import url

from . import feeds
from . import views

app_name = 'cmsplugin_newsplus'
urlpatterns = [
    url(r'^$',
        views.ArchiveIndexView.as_view(), name='news_archive_index'),

    url(r'^(?P<year>\d{4})/$',
        views.YearArchiveView.as_view(), name='news_archive_year'),

    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/$',
        views.MonthArchiveView.as_view(), name='news_archive_month'),

    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/$',
        views.DayArchiveView.as_view(), name='news_archive_day'),

    url((r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/'
         r'(?P<slug>[-\w]+)/$'),
        views.DetailView.as_view(), name='news_detail'),

    url(r'^feed/$', feeds.NewsFeed())
]

test_project/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include(
        'cmsplugin_newsplus.urls',
        namespace='cmsplugin_newsplus')),
]

cmsplugin_newsplus/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse
from django.utils import timezone

from cms.models import CMSPlugin

from . import settings


class PublishedNewsManager(models.Manager):
    """
        Filters out all unpublished and items with a publication
        date in the future
    """
    def get_queryset(self):
        return super(PublishedNewsManager, self).get_queryset().filter(
            is_published=True).filter(pub_date__lte=timezone.now())


class News(models.Model):
    """
    News
    """

    title = models.CharField(_('Title'), max_length=255)
    slug = models.SlugField(_('Slug'), unique_for_date='pub_date',
                            help_text=_('A slug is a short name which uniquely'
                                        ' identifies the news item for this'
                                        ' day'))
    excerpt = models.TextField(_('Excerpt'), blank=True)
    content = models.TextField(_('Content'), blank=True)

    is_published = models.BooleanField(_('Published'), default=False)
    pub_date = models.DateTimeField(
        _('Publication date'),
        default=timezone.now)

    created = models.DateTimeField(auto_now_add=True, editable=False)
    updated = models.DateTimeField(auto_now=True, editable=False)

    published = PublishedNewsManager()
    objects = models.Manager()

    link = models.URLField(_('Link'), blank=True, null=True,
                           help_text=_('This link will be used a absolute url'
                                       ' for this item and replaces the view'
                                       ' logic. <br />Note that by default'
                                       ' this only applies for items with '
                                       ' an empty "content" field.'))

    class Meta:
        verbose_name = _('News')
        verbose_name_plural = _('News')
        ordering = ('-pub_date', )

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        if settings.LINK_AS_ABSOLUTE_URL and self.link:
            if settings.USE_LINK_ON_EMPTY_CONTENT_ONLY and not self.content:
                return self.link
        return reverse('cmsplugin_newsplus:news_detail',
                       kwargs={'year': self.pub_date.strftime("%Y"),
                               'month': self.pub_date.strftime("%m"),
                               'day': self.pub_date.strftime("%d"),
                               'slug': self.slug})


class NewsImage(models.Model):
    news = models.ForeignKey(News, related_name='images')
    image = models.ImageField(upload_to="news_images")


class LatestNewsPlugin(CMSPlugin):
    """
        Model for the settings when using the latest news cms plugin
    """
    limit = models.PositiveIntegerField(_('Number of news items to show'),
                                        help_text=_('Limits the number of '
                                                    'items that will be '
                                                    'displayed'))

cmsplugin_newsplus/forms.py
from __future__ import absolute_import
from django import forms

from cms.plugin_pool import plugin_pool
from djangocms_text_ckeditor.widgets import TextEditorWidget
from cmsplugin_newsplus.models import News


class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = '__all__'

    def _get_widget(self):
        plugins = plugin_pool.get_text_enabled_plugins(placeholder=None,
                                                       page=None)
        return TextEditorWidget(installed_plugins=plugins)

    def __init__(self, *args, **kwargs):
        super(NewsForm, self).__init__(*args, **kwargs)
        widget = self._get_widget()
        self.fields['excerpt'].widget = widget
        self.fields['content'].widget = widget

cmsplugin_newsplus/views.py
from django.views import generic as generic_views

from . import models
from . import settings


class PublishedNewsMixin(object):
    """
    Since the queryset also has to filter elements by timestamp
    we have to fetch it dynamically.
    """
    def get_queryset(self):
        return models.News.published.all()


class ArchiveIndexView(PublishedNewsMixin, generic_views.ListView):
    """
    A simple archive view that exposes following context:

    * latest
    * date_list
    * paginator
    * page_obj
    * object_list
    * is_paginated

    The first two are intended to mimic the behaviour of the
    date_based.archive_index view while the latter ones are provided by
    ListView.
    """
    paginate_by = settings.ARCHIVE_PAGE_SIZE
    template_name = 'cmsplugin_newsplus/news_archive.html'
    include_yearlist = True
    date_field = 'pub_date'

    def get_context_data(self, **kwargs):
        context = super(ArchiveIndexView, self).get_context_data(**kwargs)
        context['latest'] = context['object_list']
        if self.include_yearlist:
            date_list = self.get_queryset().datetimes('pub_date', 'year')[::-1]
            context['date_list'] = date_list
        return context


class DetailView(PublishedNewsMixin, generic_views.DateDetailView):
    month_format = '%m'
    date_field = 'pub_date'


class MonthArchiveView(PublishedNewsMixin, generic_views.MonthArchiveView):
    month_format = '%m'
    date_field = 'pub_date'


class YearArchiveView(PublishedNewsMixin, generic_views.YearArchiveView):
    month_format = '%m'
    date_field = 'pub_date'


class DayArchiveView(PublishedNewsMixin, generic_views.DayArchiveView):
    month_format = '%m'
    date_field = 'pub_date'

cmsplugin_newsplus/templates/cmsplugin_newsplus/feeds/item_description.html
{{ obj.content|safe }}

cmsplugin_newsplus/templates/cmsplugin_newsplus/feeds/item_title.html
{{ obj.title|safe }}

cmsplugin_newsplus/templates/cmsplugin_newsplus/latest_news.html
{% load i18n %}
<div class="cmsplugin-news">
  <h2>{% trans "Latest news" %}</h2>
  <div class="content">
    {% if latest %}
    <ul>
    {% for news in latest %}
      <li>
        <a href="{{ news.get_absolute_url }}">{{ news.title }}</a>
        <span class="pub_date">{{ news.pub_date|date:"DATE_FORMAT" }}</span>
      </li>
    {% endfor %}
    </ul>
    {% else %}
    <p class="empty">{% trans "No news yet" %}</p>
    {% endif %}
    <a href="{% url "news_archive_index" %}">{% trans "Archive" %}</a>
  </div>
</div>

cmsplugin_newsplus/templates/cmsplugin_newsplus/news_archive.html
<h1>Latest news</h1>

{% for object in latest %}
<p>
  <strong>{{ object.title }}</strong>
  <br/>
  <a href="{{ object.get_absolute_url }}">Read more</a>
</p>
{% endfor %}

cmsplugin_newsplus/templates/cmsplugin_newsplus/news_archive_day.html
<h1>News for {{ day }}</h1>

<ul>
{% for object in object_list %}
  <li>
    <a href="{{ object.get_absolute_url }}">{{ object.title }}</a>
  </li>
{% empty %}
  <li>No news for this day</li>
{% endfor %}
</ul>

cmsplugin_newsplus/templates/cmsplugin_newsplus/news_archive_month.html
<h1>News for {{ month }}</h1>

<ul>
{% for object in object_list %}
  <li>
    <a href="{{ object.get_absolute_url }}">{{ object.title }}</a>
  </li>
{% empty %}
  <li>No news for this month</li>
{% endfor %}
</ul>

cmsplugin_newsplus/templates/cmsplugin_newsplus/news_archive_year.html
<h1>News for {{ year }}</h1>

<ul>
{% for date in date_list %}
  <li>
    <a href="{% url 'cmsplugin_newsplus:news_archive_month' year=date|date:'Y' month=date|date:'m'  %}">{{ date|date:"F" }}</a>
  </li>
{% empty %}
  <li>No news for this year</li>
{% endfor %}
</ul>

cmsplugin_newsplus/templates/cmsplugin_newsplus/news_detail.html
<h1>{{ object.title }}</h1>

<p>
  <span class="date">{{ object.pub_date }}</span>
  <br/>
  {{ object.content|safe }}
</p>

cmsplugin_newsplus/templates/cmsplugin_newsplus/widgets/tinymce.html
{% load i18n %}

// Global var, for storing callbacks, see below.
var editPluginPopupCallbacks = {};

{% include "cms/plugins/widgets/widget_lib.js" %}

cmsplugin_newsplus/templates/cmsplugin_newsplus/widgets/wymeditor.html
{% load i18n %}
<script type="text/javascript">

// Global var, for storing callbacks, see below.
var editPluginPopupCallbacks = {};

{% include "cms/plugins/widgets/widget_lib.js" %}



jQuery(document).ready(function(){
    jQuery('#id_{{ name }}').wymeditor({
        lang: '{{ language }}',
        skin: 'django',
        skinPath: "{{ STATIC_URL }}cms/js/wymeditor/skins/django/",
        updateSelector: 'input[type=submit],',
        updateEvent: 'click',
		logoHtml: '',
		toolsItems: [
			    {{ WYM_TOOLS }}
			],
		containersItems: [
		        {{ WYM_CONTAINERS }}
		    ],
		classesItems: [
			    {{ WYM_CLASSES }}
			],
		editorStyles: [
			{{ WYM_STYLES }}
			],
		{% if WYM_STYLESHEET %}
		stylesheet:
			{{ WYM_STYLESHEET }}
		,
		{% endif %}
        //handle click event on dialog's submit button
        postInitDialog: function( wym, wdw ) {
     
        }
    });
});
    </script>